steps:

# This step builds the container image.

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/${PROJECT_ID}/truemailserver:${SHORT_SHA}'
  - '.'
  
# This step pushes the image to Container Registry

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/truemailserver:${SHORT_SHA}'

# Deploy image to Cloud Run Google Cloud 
- name: 'gcr.io/cloud-builders/gcloud'
  id : Deploy to Cloud Run
  args:
  - 'run'
  - 'deploy'
  - 'truemailserver'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/truemailserver:${SHORT_SHA}'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'